# Generated by Django 4.1.7 on 2023-03-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_productcategory_productcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
