# Generated by Django 4.1.7 on 2023-03-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer_id',
            new_name='user',
        ),
    ]
