# Generated by Django 4.1.7 on 2023-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_apartment_address_address_appartment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_sold',
            field=models.IntegerField(default=0),
        ),
    ]
